image: docker:git
services:
  - docker:dind

stages:
  - docker_build
  # too slow, does not work
  # - docker_test
  - docker_release

.docker_repo_login: &docker_repo_login
  - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

variables:
  ROSAENLG_VERSION: 1.6.1
  DOCKER_REGISTRY: registry.gitlab.com/rosaenlg-projects/rosaenlg-java
  DOCKER_SERVER_ROOT: ${DOCKER_REGISTRY}/java-server
  DOCKER_TEST_TAG: test_${CI_COMMIT_REF_SLUG}

docker_build_server:
  stage: docker_build
  before_script:
    - *docker_repo_login
  script:
    - cd docker/
    - docker build --build-arg ROSAENLG_VERSION=$ROSAENLG_VERSION --pull -t $DOCKER_SERVER_ROOT:$DOCKER_TEST_TAG .
    - docker push $DOCKER_SERVER_ROOT:$DOCKER_TEST_TAG

docker_release_server:
  stage: docker_release
  before_script:
    - *docker_repo_login
  script:
    - docker pull $DOCKER_SERVER_ROOT:$DOCKER_TEST_TAG
    # tag and push latest
    - docker tag $DOCKER_SERVER_ROOT:$DOCKER_TEST_TAG $DOCKER_SERVER_ROOT:latest
    - docker push $DOCKER_SERVER_ROOT:latest
    # tag and push version
    - docker tag $DOCKER_SERVER_ROOT:$DOCKER_TEST_TAG $DOCKER_SERVER_ROOT:$ROSAENLG_VERSION
    - docker push $DOCKER_SERVER_ROOT:$ROSAENLG_VERSION
  # only:
  #  - master
  when: manual

